name: google-docs-to-github
description: Export Google Docs from Google Drive folder to your GitHub repository.
inputs:
  google_drive_folder_id:
    description: ID of the Google Drive folder to be exported.
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.google_drive_folder_id }}
branding:
  color: blue
  icon: download-cloud
