name: google-docs-to-github
description: Export Google Docs to GitHub.
inputs:
  github_branch:
    description: GitHub branch name where files will be pushed.
    required: false
    default: data
  google_drive_folder_id:
    description: ID of the Google Drive folder to be exported.
    required: true
runs:
  using: composite
  steps:
    - uses: r7kamura/google-docs-to-local@v0
      with:
        google_drive_folder_id: ${{ inputs.google_drive_folder_id }}
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ github.token }}
        publish_branch: ${{ inputs.github_branch }}
        publish_dir: output
branding:
  color: blue
  icon: download-cloud
