name: google-docs-to-github
description: Export Google Docs to GitHub.
inputs:
  google_drive_folder_id:
    description: ID of the Google Drive folder to be exported.
    required: true
runs:
  using: composite
  steps:
    - uses: r7kamura/google-docs-to-local@main
      with:
        google_drive_folder_id: ${{ inputs.google_drive_folder_id }}
    - uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: data
        publish_dir: output
branding:
  color: blue
  icon: download-cloud
