name: google-docs-to-github
description: Export Google Docs from Google Drive to GitHub.
inputs:
  google_drive_folder_id:
    description: ID of the Google Drive folder to be exported.
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/google-docs-to-local
      with:
        google_drive_folder_id: ${{ inputs.google_drive_folder_id }}
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ github.token }}
        publish_branch: data
        publish_dir: output
branding:
  color: blue
  icon: download-cloud
